// Import stays + categories + spokes from export JSON into target DB
// Run against prod: pnpm exec tsx --env-file=.env.production scripts/import-stays.ts
// Requires: scripts/stays-export.json (generated by export-stays.ts)

import { getPayload } from 'payload'
import config from '@payload-config'
import { readFileSync } from 'fs'
import { resolve } from 'path'

async function main() {
  const payload = await getPayload({ config })

  const raw = JSON.parse(readFileSync(resolve('scripts/stays-export.json'), 'utf8'))
  const { categories, spokes, stays } = raw as {
    categories: Array<{ id: number; name: string; slug: string; emoji?: string }>
    spokes: Array<{ id: number; name: string; slug: string; tagline?: string; description?: string; icon?: string }>
    stays: Array<Record<string, unknown>>
  }

  // ── Categories ────────────────────────────────────────────────
  console.log(`Seeding ${categories.length} categories...`)
  const catIdMap: Record<number, number> = {} // local id → prod id

  for (const cat of categories) {
    const existing = await payload.find({ collection: 'categories', where: { slug: { equals: cat.slug } }, limit: 1, depth: 0 })
    if (existing.totalDocs > 0) {
      catIdMap[cat.id] = existing.docs[0].id as number
      process.stdout.write('.')
    } else {
      const created = await payload.create({ collection: 'categories', data: { name: cat.name, slug: cat.slug, emoji: cat.emoji ?? '' } })
      catIdMap[cat.id] = created.id as number
      process.stdout.write('+')
    }
  }
  console.log(`\n✓ ${categories.length} categories`)

  // ── Spokes ────────────────────────────────────────────────────
  console.log(`Seeding ${spokes.length} spokes...`)
  const spokeIdMap: Record<number, number> = {} // local id → prod id

  for (const spoke of spokes) {
    const existing = await payload.find({ collection: 'spokes', where: { slug: { equals: spoke.slug } }, limit: 1, depth: 0 })
    if (existing.totalDocs > 0) {
      spokeIdMap[spoke.id] = existing.docs[0].id as number
      process.stdout.write('.')
    } else {
      const created = await payload.create({ collection: 'spokes', data: { name: spoke.name, slug: spoke.slug, tagline: spoke.tagline ?? '', description: spoke.description ?? '', icon: spoke.icon ?? '' } })
      spokeIdMap[spoke.id] = created.id as number
      process.stdout.write('+')
    }
  }
  console.log(`\n✓ ${spokes.length} spokes`)

  // ── Stays ─────────────────────────────────────────────────────
  console.log(`Seeding ${stays.length} stays...`)
  let created = 0, skipped = 0
  const failures: string[] = []

  for (let i = 0; i < stays.length; i++) {
    const s = stays[i] as Record<string, unknown>
    const slug = s.slug as string

    try {
      const existing = await payload.find({ collection: 'stays', where: { slug: { equals: slug } }, limit: 1, depth: 0 })
      if (existing.totalDocs > 0) { skipped++; continue }

      const localCatId = typeof s.category === 'object' && s.category !== null ? (s.category as { id: number }).id : s.category as number
      const prodCatId = catIdMap[localCatId]
      if (!prodCatId) throw new Error(`No category mapping for local id ${localCatId}`)

      const localSpokeIds: number[] = Array.isArray(s.spokes)
        ? (s.spokes as Array<{ id: number } | number>).map(sp => (typeof sp === 'object' ? sp.id : sp))
        : []
      const prodSpokeIds = localSpokeIds.map(id => {
        const mapped = spokeIdMap[id]
        if (!mapped) throw new Error(`No spoke mapping for local id ${id}`)
        return mapped
      })

      await payload.create({
        collection: 'stays',
        data: {
          slug,
          title: s.title as string,
          subtitle: (s.subtitle as string) ?? '',
          location: s.location as string,
          state: s.state as string,
          region: s.region as string,
          category: prodCatId,
          spokes: prodSpokeIds,
          platform: s.platform as string,
          affiliateUrl: s.affiliateUrl as string,
          imageUrl: (s.imageUrl as string) ?? '',
          price: s.price as number,
          rating: s.rating as number,
          reviewCount: (s.reviewCount as number) ?? 0,
          sleeps: (s.sleeps as number) ?? 0,
          bedrooms: (s.bedrooms as number) ?? 0,
          bathrooms: (s.bathrooms as number) ?? 1,
          description: (s.description as string) ?? '',
          tags: Array.isArray(s.tags) ? s.tags : [],
          featured: (s.featured as boolean) ?? false,
          editorsPick: (s.editorsPick as boolean) ?? false,
          isNew: (s.isNew as boolean) ?? false,
          workFriendly: s.workFriendly as Record<string, unknown> ?? {},
          petDetails: s.petDetails as Record<string, unknown> ?? {},
          rvDetails: s.rvDetails as Record<string, unknown> ?? {},
          evDetails: s.evDetails as Record<string, unknown> ?? {},
        },
      })

      created++
      if ((i + 1) % 25 === 0 || i === stays.length - 1) process.stdout.write(`  [${i + 1}/${stays.length}]\n`)
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      if (msg.toLowerCase().includes('slug') && (msg.toLowerCase().includes('invalid') || msg.toLowerCase().includes('unique'))) {
        skipped++
      } else {
        failures.push(`${slug}: ${msg}`)
        process.stdout.write('✗')
      }
    }
  }

  console.log(`\n─────────────────────────────────────────`)
  console.log(`✓ ${created} created | ${skipped} skipped | ${failures.length} failures`)
  if (failures.length > 0) { failures.forEach(f => console.error(`  ✗ ${f}`)); process.exit(1) }
  process.exit(0)
}

main().catch(err => { console.error(err); process.exit(1) })
